//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Display
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecEvent
    {
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Title { get; set; }
        public string Location { get; set; }
        public string Start { get; set; }
        public string EndTime { get; set; }
        public string Details { get; set; }
        public bool Prio { get; set; }
        public bool Status { get; set; }
    }
}
